### ISSUE TITLE
Add your Name as a contributor on README

### ISSUE THREAD

**Issue by adithya-s-k** [Shunya-PES/Shunya#1]
add your GitHub profile link under the contributor section of the readme

**Comment by SarthakSKumar** [comment]
I would like to work on this issue. Please assign it to me. Thanks in advance!

**Comment by akash-kamalesh** [comment]
I would like to work on this issue. Please assign it to me

**Comment by AnirudhRevanur** [comment]
I would like to work on this issue

**Comment by noughtsamar** [comment]
I would like to work on this issue.

**Comment by its-abhishek** [comment]
I would like to solve this issue

**Comment by ananyav24** [comment]
I'd like to work on this issue.
