### ISSUE TITLE
Footer Color Changes

### ISSUE THREAD

**Issue by adithya-s-k** [Shunya-PES/Shunya#12]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.

📍 Follow the Guidelines to Contribute to the Project !!

✅ To be Mentioned while taking the issue :

Full name :
GitHub Profile Link :
Email ID :
Approach for this problem:

Happy Contributing 🚀

All the best.

**Comment by SarthakSKumar** [comment]
Full name : Sarthak S Kumar
GitHub Profile Link : https://github.com/SarthakSKumar
Email ID : sskworld9742@gmail.com
Approach for this problem: Changing CSS associated with Footer. Color Changes
