### ISSUE TITLE
Fix the Position of Success/Error Message

### ISSUE THREAD

**Issue by SarthakSKumar** [Shunya-PES/Shunya#15]
Fix the Position of Success/Error Message below the Message Box, that appears on clicking 'Send Message' Button

![image](https://user-images.githubusercontent.com/81763561/188497138-eddef525-b090-4603-bbf2-3882b0e908d6.png)

Green Box Position directly below the input fields. Consider Responsive Views also.

🔴🟡 Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
"Issue Title" and "PR Title should be the same. Include issue number along with it.
Follow Contributing Guidelines & Code of Conduct before start Contributing.

📍 Follow the Guidelines to Contribute to the Project !!

✅ To be Mentioned while taking the issue :

Full name :
GitHub Profile Link :
Email ID :
Approach for this problem:

Happy Contributing 🚀

All the best.

**Comment by its-abhishek** [comment]
Full name : ABHISHEK
GitHub Profile Link : https://github.com/its-abhishek
Email ID :  abhihonnapure@gmailcom
Approach for this problem: just I'll change the position of div of id alert.

**Comment by adithya-s-k** [comment]
try to complete it within 1 day.
@its-abhishek

**Comment by adithya-s-k** [comment]
@its-abhishek good job
